SELECT
?language (SAMPLE(?wordsGroup) as ?words) (SAMPLE(?recordsGroup) as ?records)
(SAMPLE(?wikidataGroup) as ?wikidata)
(SAMPLE(?languageLabelGroup) as ?languageLabel) (SAMPLE(?codeGroup) as
?code) (SAMPLE(?wikiGroup) as ?wiki)
(SAMPLE(ROUND(1000*?wordsGroup/?recordsGroup)/10) AS ?percent)
WHERE {
  {
    SELECT ?language (SAMPLE(?recordLabelGroup) as ?wordsGroup)
(COUNT(?record) AS ?recordsGroup) {
      {
        SELECT ?language (COUNT(DISTINCT ?recordLabel) as
?recordLabelGroup) WHERE {
          ?record prop:P4 ?language .  # Filter: P4 'language' is Q21 'French'

          FILTER EXISTS {
            ?language prop:P2 entity:Q4 .# Filter: P2 'instance of' is Q4 'language'
            ?record prop:P2 entity:Q2 .  # Filter: P2 'instance of' is Q2 'record'
          }

          ?record rdfs:label ?recordLabel. # Assign value: label to ?itemLabel
        } GROUP BY ?language
      }

      ?record prop:P4 ?language .  # Filter: P4 'language' is Q21 'French'
      ?record prop:P2 entity:Q2 .  # Filter: P2 'instance of' is Q2 'record'
    } GROUP BY ?language
  }

  ?language rdfs:label ?languageLabelGroup FILTER (lang(?languageLabelGroup) = "en").
  OPTIONAL { ?language prop:P12 ?wikidataGroup }  # Assign value: language's P12 'wikidata id' into ?wikidata
  OPTIONAL { ?language prop:P13 ?codeGroup }      # Assign value: language's P13 'ISO 639-3' into ?wikidata
  OPTIONAL { ?language prop:P17 ?wikiGroup }
}
GROUP BY ?language
ORDER BY DESC(?recordsGroup)
