#
SELECT 
?language ?wikidata ?languageLabel ?code # ?wiki
(COUNT(?record) AS ?records)
#(COUNT(DISTINCT(?recordLabel)) AS ?words) 
#(ROUND(1000*?words/?records)/10 AS ?percent)
WHERE {
  ?language prop:P2 entity:Q4 .              # Filter: P2 'instance of' is Q4 'language'
  ?record prop:P4 ?language .  # Filter: P4 'language' is Q21 'French'
  ?record prop:P2 entity:Q2 .  # Filter: P2 'instance of' is Q2 'record'
  #?record rdfs:label ?recordLabel. # Assign value: label to ?itemLabel
  #FILTER ( (COUNT(?record)) > 0).
  OPTIONAL { ?language prop:P12 ?wikidata }  # Assign value: language's P12 'wikidata id' into ?wikidata
  OPTIONAL { ?language prop:P13 ?code }      # Assign value: language's P13 'ISO 639-3' into ?wikidata
  #OPTIONAL { ?language prop:P17 ?wiki }
  OPTIONAL { ?language rdfs:label ?languageLabel .
             FILTER (lang(?languageLabel) = "en"). }
}
GROUP BY ?language ?wikidata ?languageLabel ?code # ?wiki
ORDER BY DESC(?records)
